#!/bin/sh

#cleanup

rm -rf obj_dir
rm -f f1_fsm_clk.vcd


#Attach Vbuddy
~/Documents/iac/lab0-devtools/tools/attach_usb.sh

# run Verilator to translate Verilog into C++, including C++ testing
verilator -Wall --cc --trace f1_fsm_clk.sv --exe f1_fsm_clk_tb.cpp

# build C++ project via make automatically generated by Verilator 
make -j -C obj_dir/ -f Vf1_fsm_clk.mk Vf1_fsm_clk

# run executable simulation file
obj_dir/Vf1_fsm_clk